src/main/java/br/eti/cvm/springmvcjsp2/model/Pessoa.java
package br.eti.cvm.springmvcjsp2.model;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.time.Period;

@Getter
@Setter
public class Pessoa {

    private String nome;

    private String sobreNome;

    private String dataNascimento;

    public Integer getIdade() {
        return Period.between(LocalDate.parse(dataNascimento), LocalDate.now()).getYears();
    }

}

src/main/java/br/eti/cvm/springmvcjsp2/model/Usuario.java
package br.eti.cvm.springmvcjsp2.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Usuario {

    private String nome;

}

src/main/java/br/eti/cvm/springmvcjsp2/controller/BemVindoController.java
package br.eti.cvm.springmvcjsp2.controller;

import br.eti.cvm.springmvcjsp2.model.Usuario;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.context.annotation.RequestScope;
import org.springframework.web.servlet.ModelAndView;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@Controller
@RequestScope
public class BemVindoController {

    @GetMapping({"","/"})
    public ModelAndView index() {
        Usuario usuario = new Usuario();
        usuario.setNome("USUARIO TESTE");

        List<String> continentes = new ArrayList<>();
        continentes.add("América do Norte");
        continentes.add("América do Sul");
        continentes.add("Ásia");
        continentes.add("Europa");
        continentes.add("África");
        continentes.add("Oceania");
        continentes.add("Ártico");
        continentes.add("Antártica");

        Collections.sort(continentes);

        ModelAndView modelAndView = new ModelAndView("bemvindo");
        modelAndView.addObject("usuario", usuario);
        modelAndView.addObject("continentes", continentes);

        return modelAndView;
    }

}

src/main/java/br/eti/cvm/springmvcjsp2/controller/LocalesController.java
package br.eti.cvm.springmvcjsp2.controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.stream.Stream;

@Controller
public class LocalesController {



    @GetMapping("/showLocales")
    String showLocales(ModelMap modelMap) {
        Locale[] localesArray = Locale.getAvailableLocales();
        List localesList = new ArrayList<String>();

        for(Locale l: localesArray)
            localesList.add(l.toString());

        modelMap.addAttribute("locales", localesList);

        return "/show/showLocales";
    }

}

src/main/java/br/eti/cvm/springmvcjsp2/controller/PessoaController.java
package br.eti.cvm.springmvcjsp2.controller;

import br.eti.cvm.springmvcjsp2.model.Pessoa;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

@Controller
@RequestMapping()
public class PessoaController {

    private Pessoa pessoa;

    @GetMapping("/mostraformulario")
    public String mostraFormulario(@ModelAttribute("pessoa") Pessoa pessoa) {
        return "/form/mostraformulario";
    }

    @PostMapping("/processaformulario")
    public ModelAndView processaResultado(Pessoa pessoa) {
        ModelAndView modelAndView = new ModelAndView("redirect:/mostraresultado");

        this.pessoa = pessoa;

        return modelAndView;
    }

    @GetMapping("/mostraresultado")
    public ModelAndView mostraResultado() {
        ModelAndView modelAndView = new ModelAndView("/show/mostraresultado");

        modelAndView.addObject("pessoa", this.pessoa);

        return modelAndView;
    }

}

src/main/java/br/eti/cvm/springmvcjsp2/controller/ValorReaisController.java
package br.eti.cvm.springmvcjsp2.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class ValorReaisController {

    @GetMapping("/showReais")
    String showValorEmReais() {
        return "/show/showValorEmReais";
    }
}

src/main/webapp/WEB-INF/views/bemvindo.jsp
<%@ page pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
    <title>bemvindo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="/css/estilo.css">
</head>
<body>
<div>
    <span id="essespan"><c:out value="${usuario.nome}"/></span>
</div>
<div>
    <img class="estiloImagem" src="/images/PorDoSol.jpg">
</div>
<div><h2>Continentes</h2></div>
<div>
    <c:forEach items="${continentes}" var="continente">
    <p>${continente}</p>
    </c:forEach>
</div>
<script src="/js/jquery/jquery-3.6.0.min.js"></script>
</body>
</html>

src/main/webapp/WEB-INF/views/form/mostraformulario.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<!DOCTYPE html>
<html>
<head>
    <title>mostraformulario</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/WEB-INF/css/estilo.css">
</head>
<body>
<div>
    <form:form method="post" action="/processaformulario" modelAttribute="pessoa" enctype="multipart/form-data">
        <table>
            <tr>
                <td><form:label for="nome" path="nome">Nome:</form:label></td>
                <td><form:input type="text" id="nome" path="nome" /></td>
            </tr>
            <tr>
                <td><form:label for="sobreNome" path="sobreNome">Sobrenome:</form:label></td>
                <td><form:input type="text" id="sobreNome" path="sobreNome" /></td>
            </tr>
            <tr>
                <td><form:label for="dataNascimento" path="dataNascimento">Data de Nascimento (YYYY-MM-DD):</form:label></td>
                <td><form:input type="text" id="dataNascimento" path="dataNascimento" /></td>
            </tr>
            <tr>
                <td><input type="submit" value="Enviar"/></td>
            </tr>
        </table>
    </form:form>
</div>
<script src="${pageContext.request.contextPath}/WEB-INF/js/jquery/jquery-3.6.0.min.js"></script>
</body>
</html>

src/main/webapp/WEB-INF/views/show/mostraresultado.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>
<head>
    <title>mostraresultado</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/WEB-INF/css/estilo.css">
</head>
<body>
<div>
    <table>
        <tr>
            <td>Nome:</td>
            <td><c:out value="${pessoa.nome}"/></td>
        </tr>
        <tr>
            <td>Sobrenome:</td>
            <td><c:out value="${pessoa.sobreNome}"/></td>
        </tr>
        <tr>
            <td>Data de Nascimento:</td>
            <td><c:out value="${pessoa.dataNascimento}"/></td>
        </tr>
        <tr>
            <td>Idade:</td>
            <td><c:out value="${pessoa.idade}"/></td>
        </tr>
    </table>
</div>
<script src="${pageContext.request.contextPath}/WEB-INF/js/jquery/jquery-3.6.0.min.js"></script>
</body>
</html>

src/main/webapp/WEB-INF/views/show/showLocales.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="/css/estilo.css">
</head>
<body>
<div><h1>Installed Locales</h1></div>
<div>
    <c:forEach items="${locales}" var="locale">
        <p>${locale}</p>
    </c:forEach>
</div>
<script src="/js/jquery/jquery-3.6.0.min.js"></script>
</body>
</html>

src/main/webapp/WEB-INF/views/show/showValorEmReais.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<head>
    <title></title>
</head>
<body>
<div>
    <c:set var="decimal" value="10.0"/>
    <fmt:setLocale value="pt-BR"/>
    <fmt:formatNumber var="valorEmReais" type="currency" value="${decimal}" currencySymbol="R$"/>
    <p>Valor em R$: <c:out value="${valorEmReais}"/></p>
</div>
</body>
</html>